name: Build AirSignal Docker image

on:
  push:
    branches: [master]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to container registry
        # run: echo ${{ secrets.CONTAINER_REGISTRY_TOKEN }} | docker login -u ${{ secrets.CONTAINER_REGISTRY_USER }} https://gitea.local.chriphost.de --password-stdin
        uses: docker/login-action@v3
        with:
          registry: gitea.local.chriphost.de
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      - name: Build Docker image
        run: docker build . --file Dockerfile
      - name: Push Docker image
        run: docker push https://gitea.local.chriphost.de/christoph/airsignal:latest

    
